### ISSUE TITLE
Disable Amboss sounds

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce-1.12.2-Issues#6]
Amboss sounds ausschaltbar machen, und auch wenn ein Module keine Settings hat und nichts passiert hört man die Sounds dennoch, bei einem rechtsklick auf das Modul.

**Comment by Marco-MC** [comment]
This repository is only for 1.12.2 things.

https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues
